import {annualComparison,developmentBars,heatmap} from './charts.js';

function annualRow(e) {
  const r=e.annual_example,fields=[['Annual temperature','annual_mean_temp_c','°C'],['Summer temperature','summer_mean_temp_c','°C'],['Annual precipitation','annual_precip_mm','mm'],['Summer precipitation','summer_precip_mm','mm']];
  return `<div class="annual-row-preview"><p class="mini">Ontario · 2021 · one observation</p><strong>${r.mean_reported_size_ha.toFixed(0)} <small>ha/fire</small></strong><div class="annual-inputs">${fields.map(([label,key,unit])=>`<div><span>${label}</span><b>${r[key].toFixed(1)} <small>${unit}</small></b></div>`).join('')}</div></div>`;
}
export function sourceMap(map,points=true) {
  const dots=map.points.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="${2+Math.min(5,Math.log1p(p.ha)/2)}" class="fire-point" aria-hidden="true" style="--i:${i%30}"><title>Raw 2021 record · ${p.ha.toFixed(2)} reported hectares; location marker, not perimeter or prediction</title></circle>`).join('');
  return `<div class="source-map"><img src="assets/ontario-cover.png" alt="Full Ontario boundary including Toronto/GTA, Ottawa and Windsor; grey areas have no mapped woodland class"><svg viewBox="0 0 ${map.width} ${map.height}" aria-label="Raw recorded Ontario fire locations in 2021; not predictions" class="location-overlay ${points?'':'concealed'}">${dots}</svg></div>`;
}
export function angleDiagram(d=4) {
  const a=Math.PI/d,values=[-1,.3,.8,1.4];
  return `<svg viewBox="0 0 520 170" role="img" aria-label="Illustrative single-qubit phase rotations; schematic, not full entangled state">
    ${values.map((z,i)=>{const t=a*Math.tanh(z/2),phase=2*t,x=65+i*130,y=77;return `<g><ellipse cx="${x}" cy="${y}" rx="44" ry="15" class="orbit"/><circle cx="${x}" cy="${y}" r="44" class="sphere"/><line x1="${x}" y1="${y-50}" x2="${x}" y2="${y+50}" class="orbit"/><g class="state-arm"><path d="M${x} ${y} L${x+42*Math.cos(phase)} ${y+15*Math.sin(phase)}" class="state-vector"/><circle cx="${x+42*Math.cos(phase)}" cy="${y+15*Math.sin(phase)}" r="5" class="state-tip"/></g><text x="${x}" y="150" text-anchor="middle">θ = ${t.toFixed(2)}</text></g>`;}).join('')}
  </svg>`;
}
export function geometryScene(e,d=4) {
  const row=e.geometry.find(r=>r.inputs===10&&r.amplitude_pi_denominator===d);
  return `<div class="angle-side"><div class="angle-diagram">${angleDiagram(d)}</div><p class="mini">Illustrative phase rotations · radians</p><div class="angle-scale" role="group" aria-label="Ten-qubit angle amplitude">${[32,16,8,4,2].map(n=>`<button data-scale="${n}" aria-pressed="${n===d}">π/${n}</button>`).join('')}</div><div class="geometry-detail"><strong class="stat">${row.effective_rank.toFixed(2)}</strong><span class="metric-label">effective rank / 31</span><p class="mini">Mean fidelity <b>${row.off_diagonal_mean.toFixed(6)}</b></p></div></div><div class="matrix-side"><div class="heatmap">${heatmap(row)}</div><p class="mini">Measured ten-qubit training kernel</p></div>`;
}
export const scenes={
  question:e=>`<div class="hero-map">${sourceMap(e.map)}</div><div class="hero-shade"></div><div class="hero-copy"><p class="eyebrow">Ontario · Qiskit Fall Fest</p><h1>Can quantum kernels<br>estimate <em>fire size?</em></h1><p class="hero-sub">Annual mean size. Four qubits. A matched comparison.</p><div class="hero-result"><strong>657</strong><span>ha / recorded fire<br>Ontario, 2021</span></div></div><p class="hero-source">Full Ontario boundary · grey = unmapped woodland · 2021 recorded locations</p>`,
  data:e=>`<h2>One Ontario year. One row.</h2><div class="data-stage"><div class="map-window"><img src="assets/algonquin-cover.png" alt="2021 source land-cover pixels around Algonquin" class="forest-detail"><div class="province-detail">${sourceMap(e.map)}</div>${annualRow(e)}<p class="map-label">Algonquin-area land-cover pixels · 2021</p><div class="map-legend"><i style="background:#245e4b"></i>Conifer<i style="background:#97b77a"></i>Broadleaf<i style="background:#57896a"></i>Mixed<i style="background:#163c50"></i>Water</div><div class="map-steps" role="group" aria-label="Dataset view"><button data-map-stage="forest" aria-pressed="true">Pixels</button><button data-map-stage="records" aria-pressed="false">Fire records</button><button data-map-stage="annual" aria-pressed="false">Annual row</button></div></div><div class="join-story"><div class="join-source"><span>NRCan · NFDB</span><strong>784,447 ha <small>÷ 1,194 fires</small></strong><b class="target-answer">657 <small>ha/fire</small></b></div><div class="join-source climate-source"><span>ECCC · monthly climate</span><div class="climate-strips">${[55,72,43,84,60,35,66,51,76,46].map((v,i)=>`<i style="--h:${v}%;--i:${i}"></i>`).join('')}</div><small>Ten annual / seasonal summaries · schematic</small></div><p class="join-result">Join by year <span>→</span> one annual observation</p></div></div><div class="year-strip">${Array.from({length:37},(_,i)=>`<i class="${i>30?'test':''}" style="--i:${i}"><span>${1988+i}</span></i>`).join('')}</div><div class="split-label"><span><b>31</b> training years · 1988–2018</span><span><b>6</b> reused years · 2019–2024</span></div><p class="footnote">Woodland = context / separate ablation. Final predictors use climate.</p>`,
  selection:e=>`<h2>Choose four. Compare fairly.</h2><div class="selection-stage"><div class="subset-visual"><p class="mini">Ten candidate climate features</p><div class="bit-nodes">${Array.from({length:10},(_,i)=>`<i class="${[0,2,5,7].includes(i)?'chosen':''}" style="--i:${i}"><span>${[0,2,5,7].includes(i)?'1':'0'}</span></i>`).join('')}</div><div class="sample-paths"><span>Classical search</span><span>QAOA samples → SQD</span></div><svg viewBox="0 0 500 180" role="img" aria-label="Schematic candidate subsets converging to a selected four-feature subset">${[0,1,2,3,4].map(i=>`<path d="M20 ${22+i*34} C190 ${22+i*34},280 90,470 90" class="sample-line" style="--i:${i}"/>`).join('')}<circle cx="470" cy="90" r="10" fill="#18747c"/></svg><p class="mini">Four-of-ten subset schematic · 210 possibilities</p></div><div class="selector-scores">${[['Exact classical',e.selectors.exact_same_qubo],['Uniform + SQD',e.selectors.uniform_bitstring_budget],['QAOA + SQD',e.selectors.qaoa_same_qubo]].map(([n,v],i)=>`<div class="score-row"><span>${n}</span><strong>${v.toFixed(2)}</strong><i style="--w:${v}%;--i:${i}"></i></div>`).join('')}<p class="mini">Fixed-ridge MAE · ha/fire · lower is better</p></div></div><p class="footnote">Diagonal SQD returns the best sampled subset. No added optimization or quantum advantage.</p>`,
  development:e=>`<h2>Classical kernels lead.</h2><p class="subtitle">Same four inputs. Same tuning budget.</p><div class="chart">${developmentBars(e)}</div><div class="comparison-route"><span>Climate values</span><span>RBF distance <b>→</b> SVR</span><span>Qiskit state overlap <b>→</b> SVR</span></div><p class="footnote">Chronological development · no significance claim</p>`,
  evaluation:e=>`<h2>The extremes remain missed.</h2><p class="subtitle">Recorded mean hectares per fire—not total burned area.</p><div class="chart">${annualComparison(e)}</div><div class="chart-legend annual-legend">${[['Recorded mean','#c46242'],['Training mean','#7c8988'],['QSVR · 4','#18747c'],['RBF · 4','#a4b6b0']].map(([n,c])=>`<span style="color:${c}"><i></i>${n}</span>`).join('')}</div><p class="footnote">None of eleven main models beats the mean on six reused years.</p>`,
  geometry:e=>`<h2>Turn the angle. Change similarity.</h2><p class="subtitle">A measured scale sweep—not a newly fitted predictor.</p><div class="geometry-layout">${geometryScene(e)}</div><p class="footnote">Input-only diagnostic. Narrower angles can also make kernels ill-conditioned.</p>`,
  conclusions:e=>`<h2>What we can defend.</h2><div class="ending"><div><strong>77.02 <small>vs</small> 86.64</strong><span>RBF / QSVR development MAE · ha/fire</span></div><div><strong>No later-year win.</strong><span>The training mean beats every main model.</span></div><div><strong>Encoding matters.</strong><span>Similarity changes with angle scale; skill is not guaranteed.</span></div></div><p class="footnote">Next: prospective targets, independent observations and raw/log-target controls.</p>`
};
