import {encodingAppendix,resourcesAppendix} from './appendices.js';
import {scenes} from './scenes.js';
const repo='https://github.com/OhRats-Technologies/OhRats_QFF2026_uottawa/blob/main/';
const source=(file,label='Source evidence')=>`<a href="${repo+file}" target="_blank" rel="noreferrer">${label}</a>`;
const heading=(title,kicker='')=>`${kicker?`<p class="eyebrow">${kicker}</p>`:''}<h2>${title}</h2>`;

export function makeSlides(e) {
  const slides=[
    {id:'question',title:'Can quantum kernels estimate fire size?',seconds:30,html:scenes.question(e),
      notes:`Map display: the complete official Ontario boundary remains visible; grey denotes unmapped woodland classes (0/255), not absence of vegetation. Toronto/GTA, Ottawa and Windsor are WGS84 control points transformed to EPSG:3978. Our question is annual mean reported size in Ontario, not individual-fire occurrence or advance forecasting. We used actual Qiskit kernels and strong classical comparisons. The outcome is a reproducible negative comparison with a useful encoding diagnosis. The opening map shows source land-cover pixels and raw recorded 2021 coordinates, not predicted hotspots or simulated spread. ${source('docs/REPORT.md')}`},
    {id:'data',title:'One Ontario year. One row.',seconds:55,html:scenes.data(e),
      notes:`Our historical fire source is NRCan NFDB point records, not daily operational updates. We select Ontario agency records, quarantine ambiguous identities and exclude prescribed codes, then sum observed sizes and divide by their count. No coordinates, valid daily date or nearest-weather filter removes fires from the annual target. ECCC monthly measurements become station-year summaries; only stations meeting each feature's coverage threshold contribute, with equal station weights. Join aggregates by year to obtain ten climate features and one mean-size label per year. 39,616 training fires aggregate into only 31 annual rows. Years can be temporally dependent. The raw audit confirms 2021's 784,447/1,194 ratio; median fire was 0.3 ha, so large fires dominate the mean. Six later years were previously inspected in incident work. Woodland classes were screened separately and are not final predictors. The interactive map uses raw recorded 2021 locations for context, including identity-quarantined rows, distinct from the 1,194 accepted annual label records. Pixels are nearest-neighbour downsampled; location sizes are display glyphs, not fire perimeters. ${source('docs/DATA_SCHEMA.md','Schema')} · ${source('docs/DATA_REVIEW.md','Independent raw-source audit')} · ${source('docs/DATA_DOWNLOADS.md','Source acquisition')}`},
    {id:'encoding',title:'Measurements → phases → similarities.',seconds:0,backup:true,html:encodingAppendix(),
      notes:`Qiskit computes squared state overlaps through compute-uncompute. QSVR's optimization remains classical. A linear ZZ map contains single-feature phase terms and pairwise coupling, at one or two repetitions. We fit all preprocessing within training folds and compare RBF on the same inputs. Both families get four bandwidth/map choices crossed with nine C/epsilon settings. Entanglement does not guarantee useful climate interactions. ${source('docs/ANNUAL_FINAL.md','Methods and budgets')} · ${source('experiments/annual_matched.json','Matched plan')}`},
    {id:'development',title:'Classical kernels lead.',seconds:45,html:scenes.development(e),
      notes:`In the prediction comparison, both methods receive the same predeclared four climate inputs: annual/summer temperature and annual/summer precipitation. Classical RBF compares distances; Qiskit encodes bounded angles in shallow ZZ circuits and computes squared state overlap using FidelityQuantumKernel. Both feed similarities to a classical SVR optimizer; the feature map has no learned variational circuit parameters. Each family receives 36 configurations per width/fold. RBF is better in development: 77.02 versus 86.64 hectares per fire. QSVR wins one outer block and loses two. Outer blocks are 2007–2010, 2011–2014 and 2015–2018, with three inner splits for settings. The selector experiment is separate and uses fixed ridge, not these tuned kernel results. ${source('docs/results/annual-matched.json','Matched results')} · ${source('docs/results/annual-classical.json','Classical controls')}`},
    {id:'evaluation',title:'The extremes remain missed.',seconds:55,html:scenes.evaluation(e),
      notes:`Each group is one Ontario year. Orange is the total recorded hectares divided by the number of size-observed fires that year: for example, 2021 averages 656.99 hectares per fire. It is neither the total area burned, an individual fire's size nor a monthly trajectory. The grey bar repeats the training-year mean of 124.63; teal and green show the four-input QSVR and RBF estimates. High-year recorded averages dwarf those estimates. None of eleven main models beats the training mean across these six years. QSVR beats matched RBF here, but both lose to the constant, so that pairwise gain is not useful skill or quantum advantage. Model parameters and recipes froze before annual evaluation; earlier incident exposure limits independence. Same-year climate remains retrospective. ${source('docs/results/annual-final.json','All final errors')} · ${source('docs/ANNUAL_FINAL.md','Freeze and limitations')}`},
    {id:'geometry',title:'Turn the angle. Change similarity.',seconds:40,html:scenes.geometry(e),
      notes:`The rotating phase diagrams use illustrative standardized inputs [-1,0.3,0.8,1.4] and phase 2 theta for RZ applied to a superposition; they do not depict the full entangled ZZ state or measured probabilities. At pi/4, the ten-qubit training matrix is almost identity: rank 31, mean off-diagonal fidelity 0.000805. At pi/32 its entropy effective rank is 5.19 and similarity is 0.538897. Click pi/32 to demonstrate the measured matrix, then return to pi/4. This is a post-final input-only probe, not a new prediction comparison. Narrow angles can become poorly conditioned: the four-qubit narrowest map reaches 45.8 million. This scale diagnostic fitted no predictor and selected no replacement for the frozen final model. A later, separate training-only context pilot uses a fixed pi/32 recipe and a same-width zero control. Its exploratory estimates do not replace these final predictions. ${source('docs/ANNUAL_BANDWIDTH_GEOMETRY.md','Diagnostic chronology')} · ${source('docs/results/annual-bandwidth-geometry.json','Five measured scales')}`},
    {id:'conclusions',title:'What this benchmark teaches.',seconds:30,html:scenes.conclusions(e),
      notes:`Our contribution is an applied diagnostic benchmark: audited annual Ontario data, matched Qiskit/classical models and measured limitations. Encoding scale changes similarity but not necessarily predictive skill. In the separate twenty-candidate multi-start study, optimized QAOA objective coverage improves while fixed QSVR MAE worsens75.74 to85.35. The later512/1024/2048 sweep collects more candidates without restoring high feasible yield, and combined DD/twirling has mixed outcomes. Matrix RMSE and downstream MAE need separate checks. Exact enumeration of all4,845 feasible subsets takes3.07ms median on this Mac, excluding objective fitting. The new saved-prediction analysis reports sensitivity, not statistical significance; station/time controls challenge a physical interpretation. Retrospective inputs,31 training years and previously inspected evaluation limit generalization. No novelty, operational forecast or advantage claim follows. ${source('docs/CRITIQUE_RESPONSE.md','Scientific response')} · ${source('docs/SHOT_SWEEP.md','Measured shot sweep')} · ${source('docs/REPORT.md','Frozen main comparison')}`},
    {id:'selection',title:'Choose four. Compare fairly.',seconds:45,html:scenes.selection(e),
      notes:`We test feature selection separately from prediction. Eight selectors see only training years: predefined physical inputs, all ten, Lasso ranking, mutual information, exact QUBO, QAOA sampling, uniformly sampled bitstrings and random four. Ranking/objective favors training-target relevance and penalizes redundant features. Exact and sampled methods use the same objective; Lasso and mutual information are additional controls. QAOA samples subsets, then actual qiskit-addon-sqd projects the diagonal Hamiltonian into sampled bitstrings and recovers its minimum energy. With only 210 feasible four-of-ten subsets, SQD adds no improvement beyond choosing the best sampled candidate. Three sensitivity seeds and fixed ridge give 79.58 exact, 80.31 uniform and 81.66 QAOA ha/fire. These are distinct from tuned SVR scores; the main kernel comparison uses the same predeclared four inputs, not SQD-selected inputs. This is a verified application and limitation, not a speedup. ${source('docs/results/annual-selectors.json','Selector results')} · ${source('wildfire_lab/sqd_selection.py','SQD implementation')} · ${source('experiments/annual_selectors.json','Selector plan')}`},
    {id:'resources',title:'Useful shots matter.',seconds:0,backup:true,html:resourcesAppendix(e),
      notes:`This question appendix displays the actual 20-candidate/four-selected shot sweep on Marrakesh and Quebec,512/1024/2048 shots, raw and combined DD/twirling. The full sweep covers 10/16/20 pools:12 real jobs,301,056 returned shots,108 charged QPU seconds. Vertical bars are Wilson 95% shot intervals under independence, not calibration/drift uncertainty or predictive accuracy. Marrakesh raw valid counts 74/129/259; Quebec 2/10/19. Different execution/calibration conditions prevent a causal device ranking. More shots buy candidate coverage; subset quality is not monotone and full-budget classical feasible sampling is a strong reference. DD and twirling were combined, not isolated. All measured-kernel repairs stay visible in the report; the favorable rank-four cell is not a selected model. Current read-only backend metadata identifies both devices as Heron revision 2. Original final predictions are unchanged; exported PDF/PPTX retain their earlier snapshot. ${source('docs/SHOT_SWEEP.md','Full sweep and costs')} · ${source('docs/CRITIQUE_RESPONSE.md','Sensitivity and repair audit')} · ${source('docs/results/tuned-kernel-hardware.json','All measured repairs')}`},
  ];
  return ['question','data','selection','development','evaluation','geometry','conclusions','encoding','resources'].map(id=>slides.find(s=>s.id===id));
}
